import { cpSync, copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const source = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const client = process.argv[2];
if (client !== 'nur-data') {
  throw new Error('Usage: node scripts/build-client.mjs nur-data');
}

const output = join(source, 'dist', client);
const excluded = new Set(['.git', '.github', '.idea', '.vscode', 'dist', 'docs', 'scripts']);
if (existsSync(output)) rmSync(output, { recursive: true, force: true });
mkdirSync(dirname(output), { recursive: true });
for (const entry of readdirSync(source, { withFileTypes: true })) {
  if (excluded.has(entry.name) || ['.gitignore', '.DS_Store', 'README.md'].includes(entry.name)) continue;
  cpSync(join(source, entry.name), join(output, entry.name), {
    recursive: true,
    filter(path) {
      const parts = relative(source, path).split(sep);
      return !parts.some(part => excluded.has(part) || part === '.DS_Store');
    },
  });
}

// The browser profile selects the Nur Data API. HTML is branded at build time
// so the landing and legal pages are correct even before JavaScript runs.
const htmlFiles = (directory) => readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
  const path = join(directory, entry.name);
  return entry.isDirectory() ? htmlFiles(path) : entry.name.endsWith('.html') ? [path] : [];
});

for (const path of htmlFiles(output)) {
  let html = readFileSync(path, 'utf8')
    .replaceAll('support@mbrdata.com', 'support@nurdata.com')
    .replaceAll('MBR DATA', 'NUR DATA')
    .replaceAll('MBR Data', 'Nur Data')
    .replaceAll('mbrdata.com', 'nurdatasub.com')
    .replaceAll('mbr-brand.jpg', 'nur-data-logo.svg')
    .replaceAll('favicon.svg', 'nur-data-logo.svg');

  // Until Nur Data provides a number, do not route its customers to MBR Data's
  // WhatsApp. PayPlus's company page is generated by JavaScript and unaffected.
  html = html
    .replace(/ or message Nur Data support on <a href="https:\/\/wa\.me\/2347066620622"[^>]*>WhatsApp<\/a>/g, '')
    .replace(/ or contact Nur Data on <a href="https:\/\/wa\.me\/2347066620622"[^>]*>WhatsApp<\/a>/g, '')
    .replace(/<a\b(?=[^>]*\bhref="https:\/\/wa\.me\/2347066620622")[^>]*>[\s\S]*?<\/a>/g, '');
  writeFileSync(path, html);
}

copyFileSync(
  join(output, 'users', 'assets', 'img', 'nur-data-logo.svg'),
  join(output, 'admin', 'assets', 'img', 'nur-data-logo.svg'),
);

console.log(`Nur Data frontend built at ${output}`);
